apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name:  persistent
spec:
  entrypoint: main # the first template to run in the workflows        
  templates:
  - name: main           
    container: # this is a container template
      image: docker/whalesay # this image prints "welcome persistent" to the console
	  